### ISSUE TITLE
Can't install acs on yosemite

### ISSUE THREAD

**Issue by hanleyhansen** [appcelerator/acs-node-sdk#15]
I get the following error when running `sudo npm install acs` on Yosemite beta 1:

```
> acs@1.0.14 postinstall /usr/local/lib/node_modules/acs
> node scripts/config.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:815
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:815:23)
    at startup (node.js:58:13)
    at node.js:906:3
npm ERR! acs@1.0.14 postinstall: `node scripts/config.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the acs@1.0.14 postinstall script.
npm ERR! This is most likely a problem with the acs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/config.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls acs
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "acs"
npm ERR! cwd /Users/administrator2
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/administrator2/npm-debug.log
npm ERR! not ok code 0
```

Link to my full [error log](https://gist.github.com/hanleyhansen/8c0882731c709a98db51)

**Comment by cb1kenobi** [comment]
Sounds like this issue has been resolved.
